apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyflick-backend
  namespace: onlyflick
  labels:
    app: onlyflick-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyflick-backend
  template:
    metadata:
      labels:
        app: onlyflick-backend
    spec:
      containers:
      - name: onlyflick-backend
        image: barrydevops/onlyflick:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - secretRef:
            name: onlyflick-backend-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: onlyflick-backend-service
  namespace: onlyflick
  labels:
    app: onlyflick-backend
spec:
  selector:
    app: onlyflick-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
