apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyflick-backend
  namespace: onlyflick
  labels:
    app: onlyflick-backend
spec:
  replicas: 1  # Réduit à 1 pour debug
  selector:
    matchLabels:
      app: onlyflick-backend
  template:
    metadata:
      labels:
        app: onlyflick-backend
    spec:
      containers:
      - name: onlyflick-backend
        image: onlyflick-backend:latest
        imagePullPolicy: Never  # Pour images locales
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: onlyflick-backend-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60  # Plus de temps pour démarrer
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
