apiVersion: v1
kind: Service
metadata:
  name: onlyflick-backend-service
  namespace: onlyflick
  labels:
    app: onlyflick-backend
  annotations:
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  selector:
    app: onlyflick-backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
