run:
  timeout: 10m
  tests: false

linters:
  enable:
    - gosec
    - govet
    - errcheck
    - staticcheck
    - unused
    - typecheck
    - ineffassign
    - misspell
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - goconst
    - gocyclo
    - dupl

linters-settings:
  gosec:
    excludes:
      - G401
      - G501
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
