name: matchmaker
description: "OnlyFlick - Plateforme de créateurs de contenu exclusif"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  google_fonts: ^6.1.0  # Utilisez Google Fonts au lieu de polices locales
  http: ^1.2.1
  intl: any
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  path: ^1.8.3
  permission_handler: ^11.0.1
  cached_network_image: ^3.2.3
  web_socket_channel: ^2.4.0
  flutter_stripe: ^10.1.1
  json_annotation: ^4.8.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: any
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # Assets existants uniquement - supprimé les dossiers qui n'existent pas
  assets:
    - assets/images/
  
  # Supprimé la section fonts car les fichiers n'existent pas
  # Utilisez google_fonts package à la place
  
  # Si vous voulez ajouter des polices locales plus tard :
  # 1. Créez le dossier assets/fonts/
  # 2. Ajoutez vos fichiers .ttf
  # 3. Décommentez et configurez la section fonts ci-dessous
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf