name: matchmaker
description: "OnlyFlick - Plateforme de créateurs de contenu exclusif"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  http: ^1.2.1
  intl: any
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  path: ^1.8.3
  permission_handler: ^11.0.1
  cached_network_image: ^3.2.3
  web_socket_channel: ^2.4.0
  flutter_stripe: ^10.1.1
  json_annotation: ^4.8.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: any
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - fonts/

# Ajout de la section fonts pour intégrer les polices localement
fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Bold.ttf
        weight: 700
      - asset: fonts/Roboto-Italic.ttf
        style: italic
      - asset: fonts/Roboto-Light.ttf
        weight: 300
      - asset: fonts/Roboto-Medium.ttf
        weight: 500
  
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf

  - family: Inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-Bold.ttf
        weight: 700
      - asset: fonts/Inter-Medium.ttf
        weight: 500
      - asset: fonts/Inter-Light.ttf
        weight: 300
      - asset: fonts/Inter-SemiBold.ttf
        weight: 600