apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyflick-frontend
  namespace: onlyflick
  labels:
    app: onlyflick-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyflick-frontend
  template:
    metadata:
      labels:
        app: onlyflick-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: onlyflick
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        
        location /health {
            return 200 'Frontend OK';
            add_header Content-Type text/plain;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: onlyflick-frontend-service
  namespace: onlyflick
  labels:
    app: onlyflick-frontend
spec:
  selector:
    app: onlyflick-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
