apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyflick-frontend
  namespace: onlyflick
  labels:
    app: onlyflick-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlyflick-frontend
  template:
    metadata:
      labels:
        app: onlyflick-frontend
    spec:
      containers:
      - name: onlyflick-frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: flutter-web
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: flutter-web
        configMap:
          name: flutter-web-files
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
