apiVersion: v1
kind: Service
metadata:
  name: onlyflick-frontend-service
  namespace: onlyflick
  labels:
    app: onlyflick-frontend
spec:
  selector:
    app: onlyflick-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
