apiVersion: v1
kind: Service
metadata:
  name: onlyflick-frontend
  namespace: onlyflick
spec:
  selector:
    app: onlyflick-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
