apiVersion: v1
kind: Service
metadata:
  name: onlyflick-frontend-service
  namespace: onlyflick-staging
  labels:
    app: onlyflick-frontend
spec:
  selector:
    app: onlyflick-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
