version: '3.8'

services:
  db:
    image: postgres:15
    container_name: onlyflick-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onlyflick
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - onlyflick-network

volumes:
  pgdata:

networks:
  onlyflick-network:
